name: Add assignee for pull request

on:
  pull_request_target:
    branches: [ "develop" ]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
